### ISSUE TITLE
No plot is displayed

### ISSUE THREAD

**Issue by JanRuettinger** [xinleipan/gym-gridworld#2]
When I run the following code snippet, nothing really happens except that the program terminates without any errors. I expected a plot to be displayed. Am I wrong?

```
import gym  
import gym_gridworld  
env = gym.make('gridworld-v0')  
env.reset()  
for _ in range(1000):  
    env.render()  
    env.step(env.action_space.sample()) # take a random action  
```

**Comment by xinleipan** [comment]
You need to set env.verbose to "True"

`env.verbose = True`

`_ = env.reset()`
